name: Process verifier

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
  push:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Start selenium standalone
        run: |
          docker pull selenium/standalone-chrome
          docker run -d -p4444:4444 selenium/standalone-chrome
          docker ps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Verify processes
        run: pipenv run python main.py
